variable "fastly_service_name" {
  description = "The name of the Fastly service"
  type        = string
}

variable "fastly_activate" {
  description = "Conditionally prevents the Service from being activated. The apply step will continue to create a new draft version but will not activate it if this is set to false"
  type        = bool
  default     = true
}

variable "fastly_force_destroy" {
  description = "When destroying a service, the force_destroy option must be set to true in order to destroy the service"
  type        = bool
  default     = false
}

variable "fastly_stale_if_error" {
  description = "Enables serving a stale object if there is an error"
  type        = bool
  default     = false
}

variable "fastly_domain_name" {
  description = "The name of the domain to be added to the Fastly service"
  type        = string
}

variable "fastly_domain_comment" {
  description = "A comment to be added to the domain"
  type        = string
  default     = ""
}

####################
# Header Variables #
####################
variable "fastly_enable_header" {
  description = "Enable the header content block"
  type        = bool
  default     = false
}

variable "fastly_header_action" {
  description = "The action to perform on the header"
  type        = string
  default     = "set"
}

variable "fastly_header_destination" {
  description = "The destination of the header"
  type        = string
  default     = "http.Strict0Transport-Security"
}

variable "fastly_header_ignore_if_set" {
  description = "Ignore the header if it is already set"
  type        = bool
  default     = false
}

variable "fastly_header_name" {
  description = "The name of the header"
  type        = string
  default     = "Genereated by force TLS and enable HSTS"
}

variable "fastly_header_priority" {
  description = "The priority of the header"
  type        = number
  default     = 100
}

variable "fastly_header_source" {
  description = "The source of the header"
  type        = string
  default     = "\"max-age=300\""
}

variable "fastly_header_type" {
  description = "The type of the header"
  type        = string
  default     = "response"
}

variable "headers" {
  description = "List of headers and their attributes to be added to the Fastly service"
  type = list(object({
    name          = string
    action        = string
    destination   = string
    ignore_if_set = bool
    priority      = number
    source        = string
    type          = string
  }))
  default = []
}

################################
# Request Setting Variables #
################################
variable "fastly_enable_request_settings" {
  description = "Enable the request settings content block"
  type        = bool
  default     = false
}

variable "fastly_request_setting_bypass_busy_wait" {
  description = "Bypass busy wait"
  type        = bool
  default     = false
}

variable "fastly_request_setting_force_miss" {
  description = "Force miss"
  type        = bool
  default     = false
}

variable "fastly_request_setting_force_ssl" {
  description = "Force SSL"
  type        = bool
  default     = true
}

variable "fastly_request_setting_max_stale_age" {
  description = "The maximum stale age"
  type        = number
  default     = 0
}

variable "fastly_request_setting_name" {
  description = "The name of the request setting"
  type        = string
  default     = "Generated by force TLS and enable HSTS"
}

variable "fastly_request_setting_timer_support" {
  description = "Timer support"
  type        = bool
  default     = false
}


variable "fastly_backends" {
  description = "A list of backends to be added to the Fastly service"
  type = list(object({
    name                  = string
    address               = string
    port                  = number
    auto_loadbalance      = bool
    between_bytes_timeout = number
    connect_timeout       = number
    error_threshold       = number
    first_byte_timeout    = number
    max_conn              = number
    ssl_check_cert        = bool
    use_ssl               = bool
    weight                = number
  }))
  default = [
    {
      name                  = "example-backend"
      address               = "example.com"
      port                  = 80
      auto_loadbalance      = false
      between_bytes_timeout = 10000
      connect_timeout       = 1000
      error_threshold       = 0
      first_byte_timeout    = 15000
      max_conn              = 200
      ssl_check_cert        = true
      use_ssl               = false
      weight                = 100
    }
  ]
}

variable "fastly_api_key" {
  description = "The Fastly API key"
  type        = string
}